prod-reference:
	backstop reference --configPath=backstop.js --pathFile=paths --env=prod

prod-test:
	backstop test --configPath=backstop.js --pathFile=paths --env=prod

prod-report:
	backstop openReport --configPath=backstop.js --env=prod

prod-approve:
	backstop approve --configPath=backstop.js --env=prod

clone-live-reference:
	backstop reference --configPath=backstop.js --pathFile=paths --env=clone-live

clone-live-test:
	backstop test --configPath=backstop.js --pathFile=paths --env=clone-live

clone-live-report:
	backstop openReport --configPath=backstop.js --env=clone-live

clone-live-approve:
	backstop approve --configPath=backstop.js --env=clone-live

qa-reference:
	backstop reference --configPath=backstop.js --pathFile=paths --env=qa

qa-test:
	backstop test --configPath=backstop.js --pathFile=paths --env=qa

qa-report:
	backstop openReport --configPath=backstop.js --env=qa

qa-approve:
	backstop approve --configPath=backstop.js --env=qa

local-reference:
	backstop reference --configPath=backstop.js --pathFile=paths --env=local

local-test:
	backstop test --configPath=backstop.js --pathFile=paths --env=local

local-report:
	backstop openReport --configPath=backstop.js --env=local

local-approve:
	backstop approve --configPath=backstop.js --env=local
